CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(150) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    roles       VARCHAR(255) NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_roles_not_blank CHECK (btrim(roles) <> '')
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE departments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name  VARCHAR(150) NOT NULL,
    department_code  VARCHAR(30) NOT NULL UNIQUE,
    faculty          VARCHAR(150) NOT NULL,
    description      VARCHAR(1000),
    status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at       TIMESTAMPTZ,
    version          BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_departments_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE courses (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id  BIGINT NOT NULL,
    course_name    VARCHAR(150) NOT NULL,
    course_code    VARCHAR(30) NOT NULL UNIQUE,
    credit_units   INTEGER NOT NULL,
    semester       VARCHAR(20) NOT NULL,
    academic_year  VARCHAR(9) NOT NULL,
    description    VARCHAR(1000),
    status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMPTZ,
    version        BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_courses_department
        FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT,
    CONSTRAINT chk_courses_credit_units CHECK (credit_units BETWEEN 1 AND 30),
    CONSTRAINT chk_courses_semester
        CHECK (semester IN ('SEMESTER_1', 'SEMESTER_2', 'SUMMER')),
    CONSTRAINT chk_courses_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_courses_academic_year
        CHECK (academic_year ~ '^[0-9]{4}/[0-9]{4}$')
);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email  VARCHAR(255),
    action       VARCHAR(100) NOT NULL,
    detail       VARCHAR(500),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_departments_status ON departments (status);
CREATE INDEX idx_departments_deleted_at ON departments (deleted_at);
CREATE INDEX idx_courses_department_id ON courses (department_id);
CREATE INDEX idx_courses_status ON courses (status);
CREATE INDEX idx_courses_deleted_at ON courses (deleted_at);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);
